name: LOLLY
options:
  developmentLanguage: ru
  knownRegions: ["ru", "Base"]
  createIntermediateGroups: true
  bundleIdPrefix: com.kprokofyev.loyalty

configs:
  Debug: debug
  Release: release

packages:
  SnapKit:
    url: https://github.com/SnapKit/SnapKit.git
    from: 5.7.1
  PhoneNumberKit:
    url: https://github.com/marmelroy/PhoneNumberKit.git
    from: 4.1.8
  Kingfisher:
    url: https://github.com/onevcat/Kingfisher.git
    from: 8.6.1
  SwiftMessages:
    url: https://github.com/SwiftKickMobile/SwiftMessages.git
    from: 10.0.2
  CryptoSwift:
    url: https://github.com/krzyzanowskim/CryptoSwift.git
    from: 1.9.0
settings:
  base:
    VERSIONING_SYSTEM: apple-generic
    MARKETING_VERSION: 1.0
    CURRENT_PROJECT_VERSION: 0
    SWIFT_VERSION: 5.9
    CLANG_WARN_QUOTED_INCLUDE_IN_FRAMEWORK_HEADER: YES
    CLANG_ANALYZER_LOCALIZABILITY_NONLOCALIZED: YES
    CLANG_ENABLE_MODULES: YES
    GCC_WARN_UNUSED_VARIABLE: YES
    ENABLE_BITCODE: NO
    ASSETCATALOG_COMPILER_APPICON_NAME: AppIcon
    ASSETCATALOG_COMPILER_GLOBAL_ACCENT_COLOR_NAME: AccentColor
    CODE_SIGN_STYLE: Automatic
    DEVELOPMENT_ASSET_PATHS: "LOLLY/Design/Resources"

  debug:
    DEBUG_INFORMATION_FORMAT: dwarf
    GCC_OPTIMIZATION_LEVEL: 0
    SWIFT_OPTIMIZATION_LEVEL: "-Onone"
    SWIFT_ACTIVE_COMPILATION_CONDITIONS: ["DEBUG"]
    MTL_ENABLE_DEBUG_INFO: INCLUDE_SOURCE

  release:
    DEBUG_INFORMATION_FORMAT: dwarf-with-dsym
    ENABLE_NS_ASSERTIONS: NO
    MTL_ENABLE_DEBUG_INFO: NO

targets:
  LOLLY:
    type: application
    platform: iOS
    deploymentTarget: "16.0"
    sources: ["LOLLY"]
    dependencies:
      - package: SnapKit
      - package: SwiftMessages
      - package: PhoneNumberKit
      - package: Kingfisher
      - package: CryptoSwift
    bundleId: com.kprokofyev.loyalty.LOLLY
    prebuildScripts:
      - name: SwiftLint
        script: |
          if [[ $(uname -m) == "arm64" ]]; then
            export PATH="/opt/homebrew/bin:$PATH"
          fi
          if command -v swiftlint >/dev/null 2>&1; then
            swiftlint
          else
            echo "warning: SwiftLint is not installed. Install it using: brew install swiftlint"
            exit 1
          fi
        basedOnDependencyAnalysis: false
    settings:
      base:
        INFOPLIST_FILE: "LOLLY/Info.plist"
        TARGETED_DEVICE_FAMILY: "1"
